package android.support.v4.view; class ViewCompat$BaseViewCompatImpl { void a() { int a;
a=0;// .class Landroid/support/v4/view/ViewCompat$BaseViewCompatImpl;
a=0;// .super Ljava/lang/Object;
a=0;// .source "ViewCompat.java"
a=0;// 
a=0;// # interfaces
a=0;// .implements Landroid/support/v4/view/ViewCompat$ViewCompatImpl;
a=0;// 
a=0;// 
a=0;// # annotations
a=0;// .annotation system Ldalvik/annotation/EnclosingClass;
a=0;//     value = Landroid/support/v4/view/ViewCompat;
a=0;// .end annotation
a=0;// 
a=0;// .annotation system Ldalvik/annotation/InnerClass;
a=0;//     accessFlags = 0x8
a=0;//     name = "BaseViewCompatImpl"
a=0;// .end annotation
a=0;// 
a=0;// 
a=0;// # direct methods
a=0;// .method constructor <init>()V
a=0;//     .locals 0
a=0;// 
a=0;//     .prologue
a=0;//     .line 234
a=0;//     invoke-direct {p0}, Ljava/lang/Object;-><init>()V
a=0;// 
a=0;//     #p0=(Reference,Landroid/support/v4/view/ViewCompat$BaseViewCompatImpl;);
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// 
a=0;// # virtual methods
a=0;// .method public canScrollHorizontally(Landroid/view/View;I)Z
a=0;//     .locals 1
a=0;//     .param p1, "v"    # Landroid/view/View;
a=0;//     .param p2, "direction"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 236
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public canScrollVertically(Landroid/view/View;I)Z
a=0;//     .locals 1
a=0;//     .param p1, "v"    # Landroid/view/View;
a=0;//     .param p2, "direction"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 239
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getAccessibilityLiveRegion(Landroid/view/View;)I
a=0;//     .locals 1
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 357
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getAccessibilityNodeProvider(Landroid/view/View;)Landroid/support/v4/view/accessibility/AccessibilityNodeProviderCompat;
a=0;//     .locals 1
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 291
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public getAlpha(Landroid/view/View;)F
a=0;//     .locals 1
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 294
a=0;//     const/high16 v0, 0x3f800000    # 1.0f
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method getFrameTime()J
a=0;//     .locals 2
a=0;// 
a=0;//     .prologue
a=0;//     .line 279
a=0;//     const-wide/16 v0, 0xa
a=0;// 
a=0;//     #v0=(LongLo);v1=(LongHi);
a=0;//     return-wide v0
a=0;// .end method
a=0;// 
a=0;// .method public getImportantForAccessibility(Landroid/view/View;)I
a=0;//     .locals 1
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 282
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getLabelFor(Landroid/view/View;)I
a=0;//     .locals 1
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 303
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getLayerType(Landroid/view/View;)I
a=0;//     .locals 1
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 300
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getLayoutDirection(Landroid/view/View;)I
a=0;//     .locals 1
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 314
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getMeasuredHeightAndState(Landroid/view/View;)I
a=0;//     .locals 1
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 347
a=0;//     invoke-virtual {p1}, Landroid/view/View;->getMeasuredHeight()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getMeasuredState(Landroid/view/View;)I
a=0;//     .locals 1
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 352
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getMeasuredWidthAndState(Landroid/view/View;)I
a=0;//     .locals 1
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 342
a=0;//     invoke-virtual {p1}, Landroid/view/View;->getMeasuredWidth()I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getOverScrollMode(Landroid/view/View;)I
a=0;//     .locals 1
a=0;//     .param p1, "v"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 242
a=0;//     const/4 v0, 0x2
a=0;// 
a=0;//     #v0=(PosByte);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public getParentForAccessibility(Landroid/view/View;)Landroid/view/ViewParent;
a=0;//     .locals 1
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 324
a=0;//     invoke-virtual {p1}, Landroid/view/View;->getParent()Landroid/view/ViewParent;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     #v0=(Reference,Landroid/view/ViewParent;);
a=0;//     return-object v0
a=0;// .end method
a=0;// 
a=0;// .method public hasTransientState(Landroid/view/View;)Z
a=0;//     .locals 1
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 261
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public isOpaque(Landroid/view/View;)Z
a=0;//     .locals 4
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     const/4 v1, 0x0
a=0;// 
a=0;//     .line 329
a=0;//     #v1=(Null);
a=0;//     invoke-virtual {p1}, Landroid/view/View;->getBackground()Landroid/graphics/drawable/Drawable;
a=0;// 
a=0;//     move-result-object v0
a=0;// 
a=0;//     .line 330
a=0;//     .local v0, "bg":Landroid/graphics/drawable/Drawable;
a=0;//     #v0=(Reference,Landroid/graphics/drawable/Drawable;);
a=0;//     if-eqz v0, :cond_0
a=0;// 
a=0;//     .line 331
a=0;//     invoke-virtual {v0}, Landroid/graphics/drawable/Drawable;->getOpacity()I
a=0;// 
a=0;//     move-result v2
a=0;// 
a=0;//     #v2=(Integer);
a=0;//     const/4 v3, -0x1
a=0;// 
a=0;//     #v3=(Byte);
a=0;//     if-ne v2, v3, :cond_0
a=0;// 
a=0;//     const/4 v1, 0x1
a=0;// 
a=0;//     .line 333
a=0;//     :cond_0
a=0;//     #v1=(Boolean);v2=(Conflicted);v3=(Conflicted);
a=0;//     return v1
a=0;// .end method
a=0;// 
a=0;// .method public onInitializeAccessibilityEvent(Landroid/view/View;Landroid/view/accessibility/AccessibilityEvent;)V
a=0;//     .locals 0
a=0;//     .param p1, "v"    # Landroid/view/View;
a=0;//     .param p2, "event"    # Landroid/view/accessibility/AccessibilityEvent;
a=0;// 
a=0;//     .prologue
a=0;//     .line 255
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onInitializeAccessibilityNodeInfo(Landroid/view/View;Landroid/support/v4/view/accessibility/AccessibilityNodeInfoCompat;)V
a=0;//     .locals 0
a=0;//     .param p1, "v"    # Landroid/view/View;
a=0;//     .param p2, "info"    # Landroid/support/v4/view/accessibility/AccessibilityNodeInfoCompat;
a=0;// 
a=0;//     .prologue
a=0;//     .line 258
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public onPopulateAccessibilityEvent(Landroid/view/View;Landroid/view/accessibility/AccessibilityEvent;)V
a=0;//     .locals 0
a=0;//     .param p1, "v"    # Landroid/view/View;
a=0;//     .param p2, "event"    # Landroid/view/accessibility/AccessibilityEvent;
a=0;// 
a=0;//     .prologue
a=0;//     .line 252
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public performAccessibilityAction(Landroid/view/View;ILandroid/os/Bundle;)Z
a=0;//     .locals 1
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;//     .param p2, "action"    # I
a=0;//     .param p3, "arguments"    # Landroid/os/Bundle;
a=0;// 
a=0;//     .prologue
a=0;//     .line 288
a=0;//     const/4 v0, 0x0
a=0;// 
a=0;//     #v0=(Null);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public postInvalidateOnAnimation(Landroid/view/View;)V
a=0;//     .locals 2
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;// 
a=0;//     .prologue
a=0;//     .line 267
a=0;//     invoke-virtual {p0}, Landroid/support/v4/view/ViewCompat$BaseViewCompatImpl;->getFrameTime()J
a=0;// 
a=0;//     move-result-wide v0
a=0;// 
a=0;//     #v0=(LongLo);v1=(LongHi);
a=0;//     invoke-virtual {p1, v0, v1}, Landroid/view/View;->postInvalidateDelayed(J)V
a=0;// 
a=0;//     .line 268
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public postInvalidateOnAnimation(Landroid/view/View;IIII)V
a=0;//     .locals 8
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;//     .param p2, "left"    # I
a=0;//     .param p3, "top"    # I
a=0;//     .param p4, "right"    # I
a=0;//     .param p5, "bottom"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 270
a=0;//     invoke-virtual {p0}, Landroid/support/v4/view/ViewCompat$BaseViewCompatImpl;->getFrameTime()J
a=0;// 
a=0;//     move-result-wide v2
a=0;// 
a=0;//     #v2=(LongLo);v3=(LongHi);
a=0;//     move-object v1, p1
a=0;// 
a=0;//     #v1=(Reference,Landroid/view/View;);
a=0;//     move v4, p2
a=0;// 
a=0;//     #v4=(Integer);
a=0;//     move v5, p3
a=0;// 
a=0;//     #v5=(Integer);
a=0;//     move v6, p4
a=0;// 
a=0;//     #v6=(Integer);
a=0;//     move v7, p5
a=0;// 
a=0;//     #v7=(Integer);
a=0;//     invoke-virtual/range {v1 .. v7}, Landroid/view/View;->postInvalidateDelayed(JIIII)V
a=0;// 
a=0;//     .line 271
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public postOnAnimation(Landroid/view/View;Ljava/lang/Runnable;)V
a=0;//     .locals 2
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;//     .param p2, "action"    # Ljava/lang/Runnable;
a=0;// 
a=0;//     .prologue
a=0;//     .line 273
a=0;//     invoke-virtual {p0}, Landroid/support/v4/view/ViewCompat$BaseViewCompatImpl;->getFrameTime()J
a=0;// 
a=0;//     move-result-wide v0
a=0;// 
a=0;//     #v0=(LongLo);v1=(LongHi);
a=0;//     invoke-virtual {p1, p2, v0, v1}, Landroid/view/View;->postDelayed(Ljava/lang/Runnable;J)Z
a=0;// 
a=0;//     .line 274
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public postOnAnimationDelayed(Landroid/view/View;Ljava/lang/Runnable;J)V
a=0;//     .locals 3
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;//     .param p2, "action"    # Ljava/lang/Runnable;
a=0;//     .param p3, "delayMillis"    # J
a=0;// 
a=0;//     .prologue
a=0;//     .line 276
a=0;//     invoke-virtual {p0}, Landroid/support/v4/view/ViewCompat$BaseViewCompatImpl;->getFrameTime()J
a=0;// 
a=0;//     move-result-wide v0
a=0;// 
a=0;//     #v0=(LongLo);v1=(LongHi);
a=0;//     add-long/2addr v0, p3
a=0;// 
a=0;//     invoke-virtual {p1, p2, v0, v1}, Landroid/view/View;->postDelayed(Ljava/lang/Runnable;J)Z
a=0;// 
a=0;//     .line 277
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public resolveSizeAndState(III)I
a=0;//     .locals 1
a=0;//     .param p1, "size"    # I
a=0;//     .param p2, "measureSpec"    # I
a=0;//     .param p3, "childMeasuredState"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 337
a=0;//     invoke-static {p1, p2}, Landroid/view/View;->resolveSize(II)I
a=0;// 
a=0;//     move-result v0
a=0;// 
a=0;//     #v0=(Integer);
a=0;//     return v0
a=0;// .end method
a=0;// 
a=0;// .method public setAccessibilityDelegate(Landroid/view/View;Landroid/support/v4/view/AccessibilityDelegateCompat;)V
a=0;//     .locals 0
a=0;//     .param p1, "v"    # Landroid/view/View;
a=0;//     .param p2, "delegate"    # Landroid/support/v4/view/AccessibilityDelegateCompat;
a=0;// 
a=0;//     .prologue
a=0;//     .line 249
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setAccessibilityLiveRegion(Landroid/view/View;I)V
a=0;//     .locals 0
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;//     .param p2, "mode"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 363
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setHasTransientState(Landroid/view/View;Z)V
a=0;//     .locals 0
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;//     .param p2, "hasTransientState"    # Z
a=0;// 
a=0;//     .prologue
a=0;//     .line 265
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setImportantForAccessibility(Landroid/view/View;I)V
a=0;//     .locals 0
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;//     .param p2, "mode"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 286
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setLabelFor(Landroid/view/View;I)V
a=0;//     .locals 0
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;//     .param p2, "id"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 307
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setLayerPaint(Landroid/view/View;Landroid/graphics/Paint;)V
a=0;//     .locals 0
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;//     .param p2, "p"    # Landroid/graphics/Paint;
a=0;// 
a=0;//     .prologue
a=0;//     .line 310
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setLayerType(Landroid/view/View;ILandroid/graphics/Paint;)V
a=0;//     .locals 0
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;//     .param p2, "layerType"    # I
a=0;//     .param p3, "paint"    # Landroid/graphics/Paint;
a=0;// 
a=0;//     .prologue
a=0;//     .line 298
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setLayoutDirection(Landroid/view/View;I)V
a=0;//     .locals 0
a=0;//     .param p1, "view"    # Landroid/view/View;
a=0;//     .param p2, "layoutDirection"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 320
a=0;//     return-void
a=0;// .end method
a=0;// 
a=0;// .method public setOverScrollMode(Landroid/view/View;I)V
a=0;//     .locals 0
a=0;//     .param p1, "v"    # Landroid/view/View;
a=0;//     .param p2, "mode"    # I
a=0;// 
a=0;//     .prologue
a=0;//     .line 246
a=0;//     return-void
a=0;// .end method
}}
